site_name: python-template
site_description: A reusable Python project template ready for PyPI
site_author: Xianpeng Shen
copyright: "&copy; 2026 Xianpeng Shen"

repo_url: https://github.com/shenxianpeng/python-template
repo_name: shenxianpeng/python-template

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details

nav:
  - Home: index.md
  - Release: release.md
