site_name: mypackage
site_description: Replace with your project description
site_author: Xianpeng Shen
copyright: "&copy; 2024 Xianpeng Shen"

repo_url: https://github.com/shenxianpeng/mypackage
repo_name: shenxianpeng/mypackage

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details

nav:
  - Home: index.md
